# RAG evaluation for WCombSUM-RSD fusion runfile using GPU LLM
apiVersion: batch/v1
kind: Job
metadata:
  name: rag-wcombsum-rsd-k0to6
  namespace: 425krish
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: rag
        image: image-registry.openshift-image-registry.svc:5000/425krish/rag-runner:latest
        imagePullPolicy: Always
        env:
        - name: HOME
          value: /tmp
        - name: TMPDIR
          value: /tmp
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: LM_STUDIO_URL
          value: http://qwen3-4b-vllm-gpu.425krish.svc.cluster.local:8000/v1
        - name: SRC_SKIP_PACKAGE_IMPORTS
          value: "1"
        - name: SRC_SKIP_IR_EVAL
          value: "1"
        command: ["/bin/bash", "-lc"]
        args:
        - |
          set -euo pipefail
          cd /app
          python scripts/12_rag_runfile_eval.py \
            --nq_path /mnt/datasets/dpr/nq_test.json \
            --psgs_path /mnt/datasets/dpr/data/wikipedia_split/psgs_w100/psgs_w100.tsv \
            --run_path /mnt/index/dpr/fusion/wcombsum_rsd/nqtest_wcombsum_rsd.res \
            --retriever WCombSUM_RSD \
            --dataset nq_test \
            --output_root /mnt/rag/nqtest/wcombsum_rsd_k0to6 \
            --shots 0,1,2,3,4,5,6 \
            --model Qwen/Qwen3-4B-Instruct-2507 \
            --rag_variant WCombSUM_RSD_k0to6 \
            --shard_size 100 \
            --resume \
            --prompt_variant default
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
        volumeMounts:
        - name: datasets
          mountPath: /mnt/datasets
        - name: indexes
          mountPath: /mnt/index
        - name: rag
          mountPath: /mnt/rag
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: shared-datasets
      - name: indexes
        persistentVolumeClaim:
          claimName: shared-indexes
      - name: rag
        persistentVolumeClaim:
          claimName: shared-rag-results

