# Incoming: shared-datasets:/mnt/datasets/dpr/nq_test.json & shared-indexes:/mnt/index/dpr/runs/SPLADE_nqtest_all.res --- {Dict, JSON/TREC}
# Processing: SPLADE RAG generation + QA scoring --- {2 jobs: generation, evaluation}
# Outgoing: shared-rag-results:/mnt/rag/nqtest/splade_k0to6 --- {Dict, JSONL}
apiVersion: batch/v1
kind: Job
metadata:
  name: rag-splade-k0to6
  namespace: 425krish
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: rag
        image: image-registry.openshift-image-registry.svc:5000/425krish/rag-runner:latest
        imagePullPolicy: Always
        env:
        - name: HOME
          value: /tmp
        - name: TMPDIR
          value: /tmp
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: CUDA_VISIBLE_DEVICES
          value: ""
        - name: LM_STUDIO_URL
          value: http://qwen3-4b-vllm.425krish.svc.cluster.local:8000/v1
        - name: SRC_SKIP_PACKAGE_IMPORTS
          value: "1"
        - name: SRC_SKIP_IR_EVAL
          value: "1"
        command: ["/bin/bash", "-lc"]
        args:
        - |
          set -euo pipefail
          cd /app
          python scripts/12_rag_runfile_eval.py \
            --nq_path /mnt/datasets/dpr/nq_test.json \
            --psgs_path /mnt/datasets/dpr/data/wikipedia_split/psgs_w100/psgs_w100.tsv \
            --run_path /mnt/index/dpr/runs/SPLADE_nqtest_all.res \
            --retriever SPLADE \
            --dataset nq_test \
            --output_root /mnt/rag/nqtest/splade_k0to6 \
            --shots 0,1,2,3,4,5,6 \
            --model Qwen/Qwen3-4B-Instruct-2507 \
            --rag_variant SPLADE_k0to6 \
            --shard_size 100 \
            --resume
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
        volumeMounts:
        - name: datasets
          mountPath: /mnt/datasets
        - name: indexes
          mountPath: /mnt/index
        - name: rag
          mountPath: /mnt/rag
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: shared-datasets
      - name: indexes
        persistentVolumeClaim:
          claimName: shared-indexes
      - name: rag
        persistentVolumeClaim:
          claimName: shared-rag-results

